[package]
authors = ["tekjar <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.20.0"
description = "A fast, lockfree mqtt client"
repository = "https://github.com/AtherEnergy/rumqtt"
readme = "README.md"
license = "Unlicense/MIT"
keywords = ["mqtt", "iot", "async", "tokio", "futures"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-timer = "0.1"
bytes = "0.4"
mqtt3 = { git = "https://github.com/tekjar/mqtt3" }
chrono = "0.4"
jsonwebtoken = "3"
serde = "1"
serde_derive = "1"
quick-error = "1"
log = "0.3"

[dev-dependencies]
loggerv = "0.3"
