[package]
authors = ["kteza1 <k.teza1@gmail.com>"]
name = "rumqtt"
version = "0.4.0"
description = "A fast, lockfree mqtt client"
documentation = "http://ather-energy.github.io/RuMqtt/rumqtt/index.html"
repository = "https://github.com/Ather-Energy/RuMqtt"
readme = "README.md"
license = "Unlicense/MIT"
exclude = ["tests/test-utils"]
keywords = ["mqtt", "iot"]

[dependencies]
log = "0.3"
mio = "0.5"
rand = "0.3"
time = "0.1"
threadpool = "1.3"
mqtt-protocol = "0.1"

[dependencies.rustls]
git = "https://github.com/ctz/rustls"

[dev-dependencies]
env_logger = "0.3"
